# Generated by Django 5.2.14 on 2026-05-25 10:45

import file_sharing_app.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.URLField(max_length=1000)),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=file_sharing_app.models.default_expiry)),
                ('max_downloads', models.IntegerField(default=1)),
                ('current_downloads', models.IntegerField(default=0)),
            ],
        ),
    ]
