# Generated by Django 5.2.14 on 2026-05-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_sharing_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='current_downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='max_downloads',
            field=models.IntegerField(default=1),
        ),
    ]
